name: Docker Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: smithav
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: smithav/Kubernetes-challenge:latest,smithav/Kubernetes-challenge:${{ github.sha }}
