name: Docker Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # ... existing code ...
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5 # Corrected action name here
        with:
          context: .
          push: true
          tags: smithav/your-repo-name:latest,smithav/your-repo-name:${{ github.sha }}
